# Generated by Django 5.2.7 on 2025-10-24 10:42

import django.db.models.deletion
import registrations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(default=registrations.models.generate_reference_code, editable=False, help_text='Kode referensi unik pendaftaran.', max_length=15, unique=True)),
                ('full_name', models.CharField(help_text='Nama lengkap.', max_length=255)),
                ('date_of_birth', models.DateField(help_text='Tanggal lahir.')),
                ('gender', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], help_text='Jenis kelamin.', max_length=1)),
                ('phone_number', models.CharField(help_text='Nomor HP aktif.', max_length=20)),
                ('email', models.EmailField(help_text='Alamat email aktif.', max_length=254)),
                ('address', models.TextField(help_text='Alamat lengkap.')),
                ('emergency_contact_name', models.CharField(help_text='Nama kontak darurat.', max_length=255)),
                ('emergency_contact_phone', models.CharField(help_text='Nomor HP kontak darurat.', max_length=20)),
                ('shirt_size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('NS', 'Tidak Ada/Tidak Perlu')], default='NS', help_text='Ukuran baju (jika ada).', max_length=3)),
                ('agreed_to_waiver', models.BooleanField(default=False, help_text='Setuju syarat & ketentuan?')),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Menunggu Pembayaran'), ('PENDING_CONFIRMATION', 'Menunggu Konfirmasi Admin'), ('CONFIRMED', 'Pendaftaran Diterima'), ('REJECTED', 'Pendaftaran Ditolak'), ('CANCELLED', 'Dibatalkan'), ('COMPLETED', 'Selesai')], default='PENDING_PAYMENT', help_text='Status pendaftaran.', max_length=25)),
                ('payment_proof', models.ImageField(blank=True, help_text='Bukti pembayaran (jika perlu).', null=True, upload_to='payment_proofs/')),
                ('bib_number', models.CharField(blank=True, help_text='Nomor BIB.', max_length=20, null=True)),
                ('finish_time', models.DurationField(blank=True, help_text='Waktu finish.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Kategori lomba yang dipilih.', on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='events.eventcategory')),
                ('user', models.ForeignKey(help_text='User yang mendaftar.', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pendaftaran Event',
                'verbose_name_plural': 'Pendaftaran Event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='EventRegistration',
        ),
    ]
